version: "3.7"
networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  splunk_sh:
    networks:
      splunknet:
        aliases:
          - splunk_sh
    hostname: splunk_sh
    container_name: splunk_sh
    image: splunk/splunk:latest
    ports:
    - 8003:8000
    - 8089
    environment:
      - SPLUNK_PASSWORD=g8nGXBQBF
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=splunk_sh
    volumes:
      - ./bin:/opt/splunk/etc/apps/SplunkVersionControl/bin
      - ./default:/opt/splunk/etc/apps/SplunkVersionControl/default
      - ./lib:/opt/splunk/etc/apps/SplunkVersionControl/lib
      - ./lookups:/opt/splunk/etc/apps/SplunkVersionControl/lookups
      - ./metadata:/opt/splunk/etc/apps/SplunkVersionControl/metadata
      - ./README:/opt/splunk/etc/apps/SplunkVersionControl/README
      - ./static:/opt/splunk/etc/apps/SplunkVersionControl/static
      - ./test/sh_default.yml:/tmp/defaults/default.yml

  splunk_moc:
    networks:
      splunknet:
        aliases:
          - splunk_moc
    hostname: splunk_moc
    container_name: splunk_moc
    image: splunk/splunk:latest
    entrypoint:
      - /bin/sh
      - /usr/sbin/custom_init.sh
    ports:
    - 8004:8000
    - 8089
    environment:
      - SPLUNK_PASSWORD=g8nGXBQBF
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=splunk_sh
      - SPLUNK_ROLE=splunk_monitor
      - DEBUG=true
     
    volumes:
      - ./bin:/opt/splunk/etc/apps/SplunkVersionControl/bin
      - ./default:/opt/splunk/etc/apps/SplunkVersionControl/default
      - ./lib:/opt/splunk/etc/apps/SplunkVersionControl/lib
      - ./lookups:/opt/splunk/etc/apps/SplunkVersionControl/lookups
      - ./metadata:/opt/splunk/etc/apps/SplunkVersionControl/metadata
      - ./README:/opt/splunk/etc/apps/SplunkVersionControl/README
      - ./static:/opt/splunk/etc/apps/SplunkVersionControl/static
      - ./test/bkp_default.yml:/tmp/defaults/default.yml
      - ./test/install_git.yml:/tmp/install_git.yml
      - ./test/custom_init.sh:/usr/sbin/custom_init.sh
